### ISSUE TITLE
Clear queries when switching datasets

### ISSUE THREAD

**Issue by alexsb** [VCG/upset#201]
Currently queries  are preserved when switching between datasets, which doesn't make sense.

**Comment by mccalluc** [comment]
@alexsb: There still seems to be a problem: I don't know whether this is a regression, or something different. Recipe:
- Select the Simpsons data set
- Open the query dialog
- Switch to the Movies data set
- After the redraw the query dialog is open, with the old, now meaningless query. See screenshot:
<img width="460" alt="screen shot 2016-07-15 at 1 59 48 pm" src="https://cloud.githubusercontent.com/assets/730388/16884033/3a9b7fb0-4a95-11e6-91a2-05ede4a1ec47.png">
