### ISSUE TITLE
wrong cardinality for overlapping sets?

### ISSUE THREAD

**Issue by mikecho95** [VCG/upset#220]
I have a dataset with 10k subjects - 

        cblT1e2_jxc
TAC1_EAR    1    2    3    4
       0    6   15 1362  202
       1  173    0    3   58

groups common to the two groups are 173.

Here, the intersection
![image](https://cloud.githubusercontent.com/assets/144285/6399986/08238212-bdc4-11e4-8c3b-a6cc291f7090.png)

The numbers for the three-way intersection are right, but the other numbers are incorrect.  Not clear but seems like a bug?

**Comment by alexsb** [comment]
Hi Mike,

thanks for using UpSet! 

I hope that this is a misunderstanding: the degree two groups show you the exclusive intersections, i.e., the third row in the Degree 2 group shows you all the elements that are in TAC1... AND cbl... but NOT in Factor... You will reach the intersection of both of them if you also include all the elements that are in Factor... You can see that if you sum up the 82 and the 91 of degree (where all three of them are shown) you arrive at your desired 173.

If you want to see that directly, I suggest you use the "group by overlap" feature, which you can choose in the drop-down box on the top left. Here is an example for the simpons dataset: 

![image](https://cloud.githubusercontent.com/assets/2039375/6402991/04daf2a0-bdda-11e4-8ab1-a4e2fbe8a35d.png)

You have three pairwise groups - Evil/School Evil/Male and School/Male. The groups include all the two-set intersections PLUS the three set intersections. You can see clearly that there is 5 characters that are both Evil and Male but not in School, and one Evil, Male and in School - so 6 in total in that group. 

I hope that helps.

Alex

**Comment by mikecho95** [comment]
Ah - sorry.  Being very obtuse (and not looking at the quite helpful
Venn).  This is crystal clear now.  Thanks.

**Comment by alexsb** [comment]
Great!
