### ISSUE TITLE
Some sets in the selection menu are hidden

### ISSUE THREAD

**Issue by flekschas** [VCG/upset#222]
For small screens and large selections of sets, the width of the selectable sets exceeds the browser window and there is no visual clue that more sets are available.

![upset](https://cloud.githubusercontent.com/assets/932103/9367859/02d08942-468e-11e5-8102-27fd2292e69d.png)

**Comment by alexsb** [comment]
@flekschas - which OS/Browser is that?

**Comment by flekschas** [comment]
Google Chrome 44 running on OS X 10.8.5

**Comment by alexsb** [comment]
There are two little arrows below the "sort sets" caption. I didn't remember them either though... And they are a little hard to discover. It would be better if they were at the far right/left of the set list.

**Comment by flekschas** [comment]
Ah I haven't seen them before. Thanks! At first I thought the list of visible sets is only accessible be making the window larger. Since this it is possible I'll close the issue.
