### ISSUE TITLE
UpSet as htmlwidget for R?

### ISSUE THREAD

**Issue by zichner** [VCG/upset#235]
Hi,

The interactive UpSet tool is a really great. Thanks for developing it.
Would it be possible to port it into an R htmlwidget (http://www.htmlwidgets.org)?
This would make it available to a very large community and would allow to use it in RStudio directly, in Shiny apps, as well as in Rmarkdown files.

I am aware of the UpSetR package, which is very useful, but it would be great if one could also use the interactive version of UpSet in R.

FYI: @sgratzl already started to port Caleydo LineUp (https://github.com/Caleydo/lineup_htmlwidget)

Thank you very much!
Best wishes,
Thomas

**Comment by sgratzl** [comment]
do you know: https://github.com/hms-dbmi/UpSetR and https://gehlenborglab.shinyapps.io/upsetr/

**Comment by zichner** [comment]
I am aware of UpSetR as well as the shiny app. They produce static plots which is very useful for many applications. However, often it is important to have an interactive visualization (e.g., to check which elements are in an overlap, etc). Therefore, a port of the original UpSet is of high interest.

But now I noticed that there might even already be an attempt to port UpSet (in _Candela_, which is an open-source suite of interoperable web visualization components for _Kitware_‘s _Resonant_ platform):
https://github.com/Kitware/candela
https://candela.readthedocs.io/

**Comment by jeffbaumes** [comment]
@zichner Yes we have a basic working version that you can use from Candela. I don't claim that it works perfectly, here is an example posted to RPub:

https://rpubs.com/jeffbaumes/cars-upset

It was created with the following in RStudio:

```r
candela('UpSet', data=mtcars, id='_row', fields=list('cyl', 'carb'))
```

**Comment by zichner** [comment]
Thanks @jeffbaumes for your reply.
Are there any specific differences between the original UpSet and the HTMLwidget by Candela?

**Comment by jeffbaumes** [comment]
The candela version uses this library directly but puts another simpler API in front of it. The "fields" property will automatically create 0/1 sets for each value found in each field and add them to UpSet. The "sets" property will set properties that are already 0/1.

**Comment by zichner** [comment]
Thanks for the information.
