### ISSUE TITLE
Upset in asp.net

### ISSUE THREAD

**Issue by tinkupriya** [VCG/upset#238]
Can you give a version developed in asp.net with c# and direct connection to sql serverdatabase

**Comment by alexsb** [comment]
No, sorry, we don't have the resources to do that.

**Comment by tinkupriya** [comment]
Can I get ajax jquery version of it

**Comment by alexsb** [comment]
This is an open source package. Please feel free to fork and add anything you like yourself. If you want custom development, I can put you in touch with a software engineering company.
