### ISSUE TITLE
Primary graph embeddable

### ISSUE THREAD

**Issue by sulantha2006** [VCG/upset#239]
How possible is it to make this embeddable in a webpage, at least the bar graph with the intersection matrix. ?

**Comment by alexsb** [comment]
Hi Sulantha,

that's a good suggestion. Right now I don't have the resources / time to work on that, but I'll keep your issue open and once I get back to this, I'll consider it!

**Comment by alexsb** [comment]
A new version of UpSet can do that: https://vdl.sci.utah.edu/upset2/

It's not quite done yet, but a basic view with embeddings should work.
