### ISSUE TITLE
Completely baffled as to how to achieve the results on your home page

### ISSUE THREAD

**Issue by evilC** [VCG/upset#245]
Your home page is great, and makes a good case that even the layman can understand.  
However, I have absolutely no idea how to get the visualization used as the primary example of why UpSet is better  
ie this visualization:  
![](https://caleydo.org/assets/images/projects/upset//upsetr-banana.png)  
Amazing! Exactly what I want, and even a complete idiot could understand what the graph is saying...  
Not only does it appear that this data not one of the sample data sets, you don't show how to create this visualization!  
I have been stabbing away for over an hour and still am none the wiser as to how I get this view for my data set.  
Please, please expand the documentation on [this page](https://github.com/VCG/upset/wiki), and show how to create the aforementioned visualization for the provided sample data set!

**Comment by alexsb** [comment]
This is generated with the R version. https://github.com/hms-dbmi/UpSetR 
There is also a shiny app: https://gehlenborglab.shinyapps.io/upsetr/
